LIB_OSX		= m iconv objc

INC_DIR_OSX	= /usr/local/include
LIB_DIR_OSX	= /usr/local/lib

LIB_SDL2	= SDL2 SDL2main

INC_DIR_ALL = ${INC_DIR} ${INC_DIR_OSX}

LIB_DIR_ALL	= ${LIB_DIR_OSX}
LIB_ALL		= ${LIB_SDL2} ${LIB_OSX}

LIB_EXTRA	= -framework Cocoa -framework OpenGL  -framework ForceFeedback \
				-framework Carbon -framework IOKit -framework CoreAudio \
				-framework AudioToolbox -framework,AudioUnit

run:
	cd bin && ./main

clean:
	rm -R build/*
	rm ${EXE}